sudo: required
services:
  - docker

before_install:
  - docker build -t towkio/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true towkio/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-339712712433"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KE
  secret_access_key: $AWS_SECRET_KEY